### ISSUE TITLE
Null in items.collection causes fatal error on website

### ISSUE THREAD

**Issue by darceyw** [minigolf2000/winsome-website#17]
If a new item is added and collection left blank, or an existing item is updated to have blank collection, the Collections link on winsomewood has a fatal error.

I found two records in the database with null collections. Others with blank collections were '' value (and cause no error).

I assume this is a result of the ruby rails and database updated. The error is line 8 in select_controller:

    @collection_names = Item.group(:collection).having("count(*) >= 2").select("collection").size.keys.sort.reject(&:blank?)

I don't know how the application updates/inserts new records (and I looked in many places 😉 ).

Has the database schema changed (i.e. did the old schema default new value to [blank/nothing], and the new schema defaults to [null])? Or can the line above be changed to include 'nil' for the sort.reject statement?

See image for error line in production.log. I was able to replicate this on ubuntu_test. And updated the records on ubuntu_rails to have '' as the value. Error items were 16140 (new item, added in Feb/2021) and 92423 (existing item, updated on 3/1/21).

<img width="683" alt="collections_error_winsomewood" src="https://user-images.githubusercontent.com/16492766/111190085-fbf80200-8573-11eb-89aa-00049355eb96.png">

**Comment by minigolf2000** [comment]
Nice find

Hmm it's possible there were changes to the schema when I migrated the database from mysql to postgresql a looong time ago but afaik nothing has changed recently

I manually created the schema and inserted all data - the application never updates/inserts. This data can be managed via http://winsomewood.com/admin. We should hopefully be able to just use that UI to fix any faulty data that's causing errors.

I do think your suggestion to add `nil` to the `reject` statement could also work but this seems like a case of inconsistent data that should just be fixed at the data layer.

**Comment by minigolf2000** [comment]
Oh I just noticed you already updated the records to have `''` as the value, nice!

**Comment by darceyw** [comment]
Right now, adding or modifying any item is creating the inconsistent data. As there are many items records with [blank] collection, I am assuming this is a recent thing - the 2 items records that had the inconsistent data were updated (and added) this year, after the update to Ruby Rails. So if they (production dept) make another change today (or tomorrow, or ), the website will have an issue again. 

When data is managed via admin, what in that process does the update and add? That's what I was looking for... to see if there was someway to 'force' any additions (sql insert/update statements) of collection to be done with '' [blank] instead of null.

If that is not possible, then the statement in select_controller.rb needs to change. I made a change on ubuntu_test which will work. I didn't put it as part of the reject statement (I didn't know how), but as part of the 'having'. I'll check my change into the repository and you can take a look to let me know if there is a better (more "ruby") way to accomplish the same thing.

Unless of course you can tell me how to enforce that the system doesn't put null in the items.collection field, but puts [blank] instead. 

I did quite a bit of reading about blank? vs nil? vs empty? vs present?. Seemed like :blank? should have been correct, but it's not. Perhaps the error is happening in the statement in the 'having' section instead.

**Comment by minigolf2000** [comment]
From playing around with a local REPL, I think the bug is actually in the `sort`. It complains when comparing a string value to a nil value since it doesn't know which one is greater than the other. I think the fix is to swap the sort with the reject. It was just a mistake to do it in that order.

```ruby
[18] figma(main)> ["a", "b", nil, nil, "c", "", "1"].sort.reject(&:blank?)
ArgumentError: comparison of String with nil failed
from (pry):18:in `sort'
[19] figma(main)> ["a", "b", nil, nil, "c", "", "1"].reject(&:blank?).sort
=> ["1", "a", "b", "c"]
```

For bugs like this I find it useful to use the [Rails interactive shell](https://github.com/minigolf2000/winsome-website#rails-interactive-shell) to run simple commands and debug. Lmk if those setup instructions work!

The app uses the [RailsAdmin](https://github.com/sferik/rails_admin) gem to power this admin UI.

Config file: https://github.com/minigolf2000/winsome-website/blob/master/config/initializers/rails_admin.rb
Gemfile line: https://github.com/minigolf2000/winsome-website/blob/master/Gemfile#L30

It's probably annoying to try to edit what RailsAdmin does, but thinking about this problem more I do think using null to represent empty is probably better than using `''` to represent empty like I was originally doing. In the long run it could be nice to run a batch sql query that updates all `''` collection values to instead be null. This is not that important to do
